import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center w-screen min-h-screen p-2 overflow-x-hidden text-white">{children}</body>
    </html>
  );
}
